name: Build and Push Docker Image on Release

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          sudo lsmod
          sudo modinfo xt_NFQUEUE
          sudo iptables -j NFQUEUE --help
